# 测试点赞接口
POST http://localhost:8084/video/like
Content-Type: application/x-www-form-urlencoded
token: eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_6tWKi5NUrJSSknMy03MLtUNDXYNUtJRSq0oULIyNDc1NjUxNDO11FEqLU4t8kxRsjKqBQA7ZJ38MgAAAA.Hx_lbnuRh9LIr0G8PuISLVhh_-rpSeaVRkdcWEfqCrJ6X-U2uOYPMsll_tE70M-qrzrxqY0iDCis-LGYw1cvIA

videoId = 1

###

# 测试取消点赞接口
DELETE http://localhost:8084/video/like
Content-Type: application/x-www-form-urlencoded
token: eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_6tWKi5NUrJSSknMy03MLtUNDXYNUtJRSq0oULIyNDc1NjUxNDO11FEqLU4t8kxRsjKqBQA7ZJ38MgAAAA.Hx_lbnuRh9LIr0G8PuISLVhh_-rpSeaVRkdcWEfqCrJ6X-U2uOYPMsll_tE70M-qrzrxqY0iDCis-LGYw1cvIA

videoId = 1

###

# 测试视频点赞数接口(带token)
GET http://localhost:8084/video/like?videoId=1
token: eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_6tWKi5NUrJSSknMy03MLtUNDXYNUtJRSq0oULIyNDc1NjUxNDO11FEqLU4t8kxRsjKqBQA7ZJ38MgAAAA.Hx_lbnuRh9LIr0G8PuISLVhh_-rpSeaVRkdcWEfqCrJ6X-U2uOYPMsll_tE70M-qrzrxqY0iDCis-LGYw1cvIA
Content-Type: application/x-www-form-urlencoded

###

# 测试视频点赞数接口(无token)
GET http://localhost:8084/video/like?videoId=1
Content-Type: application/x-www-form-urlencoded

###

# 测试弹幕接口
POST http://localhost:8084/danmaku
Content-Type: application/json

{
  "userId": 1,
  "videoId": 1,
  "content": "测试弹幕内容"
}

###

GET http://localhost:8084/danmaku?videoId=1&startTime=2025-07-01 00:00:00&endTime=2025-07-11 23:00:00

###

GET http://localhost:8084/danmaku?videoId=1

###

POST localhost:8084/video/collection
token: eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_6tWKi5NUrJSSknMy03MLtUNDXYNUtJRSq0oULIyNDc1MTYzMDG01FEqLU4t8kxRsjKqBQApbKFzMgAAAA.JY-47Koh-umd2HdWahmte7j78TF88lcvnlJ2bY6Xl7tE-VLs3Jetk7GBe2BVneZMhwTHzrrJI8EBlRoz_727LA
Content-Type: application/json

{
  "userId": 2,
  "videoId": 1,
  "groupId": 1,
  "createAt": ""
}

###